---
title: "ME315A_Lab07_LuizCelin"
author: "Luiz Fernando Celin"
format: pdf
editor: visual
---

```{r setup}
library(RSQLite)
library(tidyverse)
```

# Questão 1
```{r}
path <- ("archive")
fname <- file.path(path, "database.sqlite3")

conn <- dbConnect(SQLite(), fname)

dbListTables(conn)
```

# Questão 2

Plano:
instructors(id) -> teachings(instructor_id) -> sections(course_offering_uuid) -> subject_memberships(course_offering_uuid) -> subjects(code) 

```{r professores}
dbGetQuery(conn, "SELECT DISTINCT instructors.id, instructors.name FROM instructors
                  INNER JOIN teachings
                      ON instructors.id = teachings.instructor_id
                  INNER JOIN sections
                      ON teachings.section_uuid = sections.uuid
                  INNER JOIN subject_memberships
                      ON sections.course_offering_uuid = subject_memberships.course_offering_uuid
                  INNER JOIN subjects
                      ON subject_memberships.subject_code = subjects.code
                  WHERE subjects.abbreviation = 'STAT'
                  ORDER BY instructors.name;")
```

```{r quantidade}
dbGetQuery(conn, "SELECT COUNT(DISTINCT instructors.id) AS quantidade FROM instructors
                  INNER JOIN teachings
                      ON instructors.id = teachings.instructor_id
                  INNER JOIN sections
                      ON teachings.section_uuid = sections.uuid
                  INNER JOIN subject_memberships
                      ON sections.course_offering_uuid = subject_memberships.course_offering_uuid
                  INNER JOIN subjects
                      ON subject_memberships.subject_code = subjects.code
                  WHERE subjects.abbreviation = 'STAT'")
```
### Quem é o professor mais difícil?
```{r professor_dificil}
dbGetQuery(conn, "SELECT instructors.name, SUM(
                    a_count * 4.0 + ab_count *3.5 + b_count * 3.0 +
                    bc_count * 2.5 + c_count * 2.0 +d_count * 1.0 + f_count * 0.0)/
                    SUM(a_count + ab_count + b_count + bc_count + c_count + d_count
                    + f_count) AS MEDIA_NOTAS FROM instructors
                    
                  INNER JOIN teachings 
                      ON teachings.instructor_id = instructors.id
                  INNER JOIN sections 
                      ON sections.uuid = teachings.section_uuid
                  INNER JOIN course_offerings 
                      ON course_offerings.uuid = sections.course_offering_uuid
                  INNER JOIN grade_distributions 
                      ON grade_distributions.course_offering_uuid = course_offerings.uuid
                  INNER JOIN subject_memberships 
                      ON subject_memberships.course_offering_uuid = sections.course_offering_uuid
                  INNER JOIN subjects 
                      ON subjects.code = subject_memberships.subject_code
                  WHERE subjects.abbreviation = 'STAT'
                  GROUP BY instructors.name
                  HAVING SUM(a_count + ab_count + b_count +
                  bc_count + c_count + d_count + f_count) > 0
                  ORDER BY MEDIA_NOTAS
                  LIMIT 1")
```

### Quem é o professor mais fácil?
```{r}
dbGetQuery(conn, "SELECT instructors.name, SUM(
                    a_count * 4.0 + ab_count * 3.5 + b_count * 3.0 +
                    bc_count * 2.5 + c_count * 2.0 + d_count * 1.0 + f_count * 0.0)/
                    SUM(a_count + ab_count + b_count + bc_count + c_count + d_count
                    + f_count) AS MEDIA_NOTAS FROM instructors
                    
                  INNER JOIN teachings 
                      ON teachings.instructor_id = instructors.id
                  INNER JOIN sections 
                      ON sections.uuid = teachings.section_uuid
                  INNER JOIN course_offerings 
                      ON course_offerings.uuid = sections.course_offering_uuid
                  INNER JOIN grade_distributions 
                      ON grade_distributions.course_offering_uuid = course_offerings.uuid
                  INNER JOIN subject_memberships 
                      ON subject_memberships.course_offering_uuid = sections.course_offering_uuid
                  INNER JOIN subjects 
                      ON subjects.code = subject_memberships.subject_code
                  WHERE subjects.abbreviation = 'STAT'
                  GROUP BY instructors.name
                  HAVING SUM(a_count + ab_count + b_count +
                  bc_count + c_count + d_count + f_count) > 0
                  ORDER BY MEDIA_NOTAS DESC
                  LIMIT 3")
```

### Qual é a disciplina mais difícil?
```{r}
dbGetQuery(conn, "SELECT courses.name, SUM(
                    a_count * 4.0 + ab_count * 3.5 + b_count * 3.0 +
                    bc_count * 2.5 + c_count * 2.0 + d_count * 1.0 + f_count * 0.0)/
                    SUM(a_count + ab_count + b_count + bc_count + c_count + d_count +
                    f_count) AS MEDIA_NOTAS FROM courses
                  INNER JOIN course_offerings 
                      ON course_offerings.course_uuid = courses.uuid
                  INNER JOIN grade_distributions 
                      ON grade_distributions.course_offering_uuid = course_offerings.uuid
                  INNER JOIN subject_memberships 
                      ON subject_memberships.course_offering_uuid = course_offerings.uuid
                  INNER JOIN subjects 
                      ON subjects.code = subject_memberships.subject_code
                  WHERE subjects.abbreviation = 'STAT'
                  GROUP BY courses.uuid, courses.name
                  HAVING SUM(a_count + ab_count + b_count +
                  bc_count + c_count + d_count + f_count) > 0
                  ORDER BY MEDIA_NOTAS
                  LIMIT 1")
```

### Qual é a disciplina mais fácil?
```{r}
dbGetQuery(conn, "SELECT courses.name, SUM(
                    a_count * 4.0 + ab_count * 3.5 + b_count * 3.0 +
                    bc_count * 2.5 + c_count * 2.0 + d_count * 1.0 + f_count * 0.0)/
                    SUM(a_count + ab_count + b_count + bc_count + c_count + d_count +
                    f_count) AS MEDIA_NOTAS FROM courses
                  INNER JOIN course_offerings 
                      ON course_offerings.course_uuid = courses.uuid
                  INNER JOIN grade_distributions 
                      ON grade_distributions.course_offering_uuid = course_offerings.uuid
                  INNER JOIN subject_memberships 
                      ON subject_memberships.course_offering_uuid = course_offerings.uuid
                  INNER JOIN subjects 
                      ON subjects.code = subject_memberships.subject_code
                  WHERE subjects.abbreviation = 'STAT'
                  GROUP BY courses.uuid, courses.name
                  HAVING SUM(a_count + ab_count + b_count +
                  bc_count + c_count + d_count + f_count) > 0
                  ORDER BY MEDIA_NOTAS
                  LIMIT 1")
```

```{r}
dbDisconnect(conn)
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```











