---
title: "Lab_02"
author: "Luiz Fernando Celin"
format: pdf
editor: visual
---

```{r r setup, include=FALSE}
#install.packages("tidyverse")
#install.packages("devtools")
#devtools::install_github("jayjacobs/ggcal")
#install.packages("ggplot2")
#?ggcall

library(tidyverse)
library(readr)
library(dplyr)
library(ggcal)
library(ggplot2)
```

## QUESTÃO 1
Para calcular o percentual de voos que tiveram atraso na chegada superior a 10 minutos, precisamos de número total de voos e número de voos atrasados (ARRIVAL_DELAY > 10).

## QUESTÃO 2
```{r}
getStats <- function(input, pos) {
  input %>%
    filter(AIRLINE == "AA" |
       AIRLINE == "DL" |
       AIRLINE == "UA" |
       AIRLINE == "US") %>%
    filter(!is.na(ARRIVAL_DELAY)) %>%
    group_by(MONTH, DAY, AIRLINE) %>%
    summarise(
      total = n(),
      atrasados = sum(ARRIVAL_DELAY > 10)
    )
}
```

## QUESTÃO 3
```{r}

resultado <- read_csv_chunked(
  "flights.csv.zip",
  callback = DataFrameCallback$new(getStats),
  chunk_size = 1e6,
  col_types = cols_only(
    MONTH = col_integer(),
    DAY = col_integer(),
    AIRLINE = col_character(),
    ARRIVAL_DELAY = col_double()
  )
)
```

## QUESTÃO 4
```{r}
computeStats <- function(stats) {
  
  stats %>%
    group_by(MONTH, DAY, AIRLINE) %>%
    summarise(
      total = sum(total),
      atrasados = sum(atrasados)
    ) %>%
    mutate(
      Perc = atrasados / total,
      Data = as.Date(paste(2015, MONTH, DAY, sep = "-"))
    ) %>%
    select(Cia = AIRLINE, Data, Perc)
}

stats_final <- computeStats(resultado)
```

## QUESTÃO 5
```{r}
paleta <- scale_fill_gradient(
  low = "#4575b4",
  high = "#d73027"
)

baseCalendario <- function(stats, cia) {
  
  dados <- stats %>%
    filter(Cia == cia)
  
  ggcal(dados$Data, dados$Perc)
}

cAA <- baseCalendario(stats_final, "AA")
cDL <- baseCalendario(stats_final, "DL")
cUA <- baseCalendario(stats_final, "UA")
cUS <- baseCalendario(stats_final, "US")

cAA + paleta + ggtitle("Atrasos - AA")
cDL + paleta + ggtitle("Atrasos - DL")
cUA + paleta + ggtitle("Atrasos - UA")
cUS + paleta + ggtitle("Atrasos - US")
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```



