---
title: "Lista04_LuizCelin"
author: "Luiz Fernando Celin"
format: pdf
---

# Lista 04
```{r}
library(DBI)
library(RSQLite)

con <- dbConnect(RSQLite::SQLite(), "me315.sqlite")
```

## Questão 1

    ```{sql connection=con}
    SELECT * FROM PRESERVE
    WHERE PNO IN (2, 4, 6, 8, 10)
    ```

## Questão 2

    ```{sql connection=con}
    SELECT * FROM PRESERVE
    WHERE PNAME NOT IN ('DANCING PRAIRIE', 'MULESHOE RANCH', 'MCELWAIN-OLSEN', 'TATKON')
    ```

## Questão 3

    ```{sql connection=con}
    SELECT * FROM PRESERVE
    WHERE PNO BETWEEN 3 AND 10
    ```

## Questão 4

    ```{sql connection=con}
    SELECT * FROM PRESERVE
    WHERE PNO NOT BETWEEN 3 AND 10
    ```

## Questão 5

    ```{sql connection=con}
    SELECT STATE, PNO, ACRES FROM PRESERVE
    WHERE (STATE <> 'MT') AND (STATE <> 'AZ') AND (ACRES NOT BETWEEN 50 AND 800)
    ORDER BY PNO DESC
    ```

## Questão 6

    ```{sql connection=con}
    SELECT PNAME FROM PRESERVE
    WHERE PNAME BETWEEN 'D' AND 'DZZZ'
    ```

## Questão 7
    ```{sql connection=con}
    SELECT PNAME FROM PRESERVE
    WHERE PNAME LIKE '%TOWN%'
    ```

## Questão 8

    ```{sql connection=con}
    SELECT PNAME FROM PRESERVE
    WHERE PNAME LIKE '%PRAIRIE'
    ```

## Questão 9

    ```{sql connection=con}
    SELECT PNAME FROM PRESERVE
    WHERE PNAME LIKE '%ING%'
    ```

## Questão 10

    ```{sql connection=con}
    SELECT PNAME FROM PRESERVE
    WHERE PNAME LIKE '%E'
    ```

## Questão 11

    ```{sql connection=con}
    SELECT PNAME FROM PRESERVE
    WHERE PNAME LIKE '%ME%'
    ```

## Questão 12

    ```{sql connection=con}
    SELECT PNAME FROM PRESERVE
    WHERE PNAME LIKE '%M%E%'
    ```

## Questão 13

    ```{sql connection=con}
    SELECT PNAME FROM PRESERVE
    WHERE PNAME LIKE '_A%'
    ```

## Questão 14

    ```{sql connection=con}
    SELECT PNAME FROM PRESERVE
    WHERE PNAME LIKE '% %'
    ```

## Questão 15

    ```{sql connection=con}
    SELECT PNAME FROM PRESERVE
    WHERE (PNAME LIKE '%FARM%') OR (PNAME LIKE '%SWAMP%') OR (PNAME LIKE '%PRAIRIE%')
    ```

## Questão 16

    ```{sql connection=con}
    SELECT PNAME FROM PRESERVE
    WHERE (PNAME LIKE '%-%') OR (PNAME LIKE '%.%')
    ```

## Questão 17

    ```{sql connection=con}
    SELECT PNAME FROM PRESERVE
    WHERE PNAME LIKE '____R%PRAIRIE'
    ```

## Questão 18

    ```{sql connection=con}
    SELECT * FROM EMPLOYEE
    WHERE DNO IN (10, 40)
    ```

## Questão 19

    ```{sql connection=con}
    SELECT * FROM EMPLOYEE
    WHERE DNO NOT IN (10,40)
    ```

## Questão 20

    ```{sql connection=con}
    SELECT * FROM EMPLOYEE
    WHERE SALARY BETWEEN 500 AND 2000
    ```

## Questão 21

    ```{sql connection=con}
    SELECT * FROM EMPLOYEE
    WHERE SALARY NOT BETWEEN 500 AND 2000
    ```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
